changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Features
      labels:
        - enhancement
        - feat
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Documentation
      labels:
        - documentation
        - docs
    - title: CI And Maintenance
      labels:
        - ci
        - chore
        - build
    - title: Other Changes
      labels:
        - "*"
